# Override these settings with your own
languageCode = "es-es"
title = "Jesús Millán"
baseURL = "https:/jmillandev.github.io"
theme = "hugo-theme-codex" 
copyright = "© {year}"

# Add your Disqus shortname here.
disqusShortname = "jmillandev"

# Add your Google Analytics identifier: UA-XXXXXXXX-X
googleAnalytics = "" 

# Optional params
[params]
  avatarurl = "/images/avatar.jpeg"

  # Follow the Hugo date/time format reference here: 
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "Jan 2 2006"

  twitter = "https://twitter.com/jmillandev"
  github = "https://github.com/jmillandev"
  linkedin = "https://www.linkedin.com/in/jmillandev-42664412a/"
  
  # Titles for your icons (shown as tooltips), and also their display order.
  # Currently, these icons are supported: 
  #   "Twitter", "GitHub", "Email", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube"
  iconOrder = ["Twitter", "GitHub", "LinkedIn"]

  # Metadata for Twitter cards, defaults to params.twitter
  twitterSite = "@jmillandev"
  twitterAuthor = "@jmillandev"

  # Set to true to display page title in table of contents in blog posts.
  showPageTitleInTOC = false

# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
[markup]
  [markup.highlight]
    codeFences = false
    
  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

# Controls the navigation
[[menu.main]]
  identifier = "about"
  name = "About"
  title = "About"
  url = "/"

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  title = "Blog"
  url = "/blog/"

[[menu.main]]
  identifier = "apuntes"
  name = "Apuntes"
  title = "Apuntes"
  url = "/apuntes/"
